### PR TITLE
Allow the ability to send to groups as well as users

### PR DESCRIPTION
**Pull request by volksman**
This PR allows you to specify using a send to group form.  This lets the end user select any number of users and/or groups to send the message to.

### CODE REVIEW

**Comment by grahamu** [comment]
@volksman this looks like a useful addition. How about adding a docstring to `NewMessageFormGroup` explaining how the form fields are evaluated and processed to determine what users get the message, since that's not exactly straightforward? Thanks!

**Comment by volksman** [comment]
I've changed it around a little to allow people to define their own form flavours.  I'm sure some would want only group selection or maybe one or the other.  I'm not sure if it's worth packaging the MultipleGroup form I created with pinax.messages but will leave that to you guys.

**Comment by paltman** [comment]
I wonder if we could abstract this so it could be any collection of users rather than the `auth.Group` collection.  For example, what if I wanted to send messages to a particular `Team` (from `pinax-teams`) or check off a list of users I know from some domain modeling relationship?

Could we structure this in a way that didn't depend on the group and allowed the site developer to inject the functionality for addressing multiple users?  With a hookset or call back or something?

**Comment by volksman** [comment]
Hi @paltman I felt it was best to allow the user to decide how to collect the list of users regardless of the app and the best way for that to happen was at the Form level.  So that's why I changed to the ability of passing in a form of the users choice. 

Let me know if I'm flawed in my logic on that one.

**Comment by volksman** [comment]
ping @paltman

**Comment by volksman** [comment]
Crickets..........

**Comment by dmpe** [comment]
Ping @paltman from me as well

**Comment by morenoh149** [comment]
@KatherineMichel what's blocking this? outside the scope of the project?

**Comment by KatherineMichel** [comment]
@morenoh149 Sorry for the delay. Not sure. I will check it out.

**Comment by volksman** [comment]
See PR#60 for an update

**Pull request closed without merging**
