### PR TITLE
Use class-based views and update tests and test configuration

### PR DESCRIPTION
**Pull request by grahamu**

### CODE REVIEW

**Comment by ossanna16** [comment]
You're killing it with the PRs @grahamu ;)

**Comment by grahamu** [comment]
Thanks @ossanna16, just doing what I can to unblock the simple apps in Pinax 16.04 candidate list.

**Comment by grahamu** [comment]
This PR builds on and supersedes PR #17.

**Comment by ossanna16** [comment]
Thanks a ton! We appreciate all your great work on Pinax!

**Comment by grahamu** [comment]
OK, that last commit provides the correct new logic for `Message.new_reply()`, and completes this PR.

**Pull request closed without merging**
