### PR TITLE
remove all dependency on DUA

### PR DESCRIPTION
**Pull request by volksman**

### CODE REVIEW

**Comment by paltman** [comment]
We should continue to support DUA, but make it optional.

For example, we do this in `pinax-stripe`:

https://github.com/pinax/pinax-stripe/blob/bf93fe374e03861a965d3a129eb9bdb189eee7ca/pinax/stripe/mixins.py#L6-L9

This has the benefit if we are using `django-user-accounts` this app will continue to work nicely but if you are not you can gracefully fall back to Django's internals.

**Comment by volksman** [comment]
@paltman updated!

**Comment by paltman** [comment]
Thanks!

**Comment by grahamu** [comment]
Nice fix @volksman

**Pull request merged**
